### ISSUE TITLE
Button 1, Button 2 & Button 3

### ISSUE THREAD

**Issue by wfhstudio** [h-RAT/EvilCrowRF_Custom_Firmware_CC1101_FlipperZero#1]
h-RAT,
Thanks for this sharing. Trying to make one button a bit confused the pin for Button 1,2 and 3. Would you please tell me? Thanks in Advance

**Comment by h-RAT** [comment]
> h-RAT, Thanks for this sharing. Trying to make one button a bit confused the pin for Button 1,2 and 3. Would you please tell me? Thanks in Advance

Hey, the main firmware use EvilcrowRF V2 pins:

// Push Button Pins
push1=34;
push2=35;

**Comment by xzibit1** [comment]
THANKS FOR SENDING ME PROGRAM KAIJU FOR EWIL CROW!✌👌😃
I GAWE IT TO MY PROGRAMMER TO CUSTOMIZE IT LIKE YOU,WROTE IT!
DO I NEED A SECEND ONE TO PERFORM ROLLING CODE ATTACK??IS IT DUABLE WITH
FLIPPER ZERO AND EWIL CROW RF V2????🤔
IM WAITING FOR MY BOOSTER CC1101 FOR FLIPPER ZERO SO AT THE MOMENT CANT
TELL WHICH NUMBER...🤯✌
I BUY SO MANY THINGS ,INSTEAD I SCHOUD HAWE BOUGT PANDA RF ROUGE!!!!😅
IF YOU HAWE AURDINO ROLLYAM,OR CAPIBILLITY TO MAKE SONETHING AS ROLLYAM
,LIKE SAMMY ,S WE CAN WITH NO PROBLEM COME TO AGREEMENT!!!IM IN
CROATIA...✌💎🍍
SO TELL ME WHATT YOU NEED I PROWIDE TO YOU....OR SCHOUD O BUY PANDA RF
ROUGE AND IT GOES SMOOD??
HOPE TO HEAR FROM YOU...💎💯🥂

ned, 18. lip 2023. 11:06 h-RAT ***@***.***> je napisao:
