### ISSUE TITLE
[Question]how to setting jamming device to connect on AP device

### ISSUE THREAD

**Issue by reverseideol0gy** [h-RAT/EvilCrowRF_Custom_Firmware_CC1101_FlipperZero#10]
on the title. I use 2 evil crow rf v.2. on main evil crow connect to hotspot or my AP.
when I need to play rolljam attack. I need to re-config main evil crow back to AP mode. sometime I forgot default ssid and password it waste time to search about this.
can you advice this for config jamming device

**Comment by reverseideol0gy** [comment]
and another question about power management function how to use it on this firmware.

**Comment by xzibit1** [comment]
My frend i now only the password for ewil crow rf v2 is 123456789..for wi fi connectinon ..ewefthing else sorry , but i sold m, e.crow ,had no progrres ,and it,S not exatly usefull and SIMPLE as other better dewices out online..
✌🌈💪🏽

**Comment by xzibit1** [comment]
I gawe my..away...no good dewice

**Comment by h-RAT** [comment]
> on the title. I use 2 evil crow rf v.2. on main evil crow connect to hotspot or my AP. when I need to play rolljam attack. I need to re-config main evil crow back to AP mode. sometime I forgot default ssid and password it waste time to search about this. can you advice this for config jamming device

Hi, you must place the main device in AP mode with SSID: "ECRF" and password "123456789"

The second device will connect to the first when you use rolljam/rollback

And no power management in this firmware
