### ISSUE TITLE
evil crow rf v2 error when flashing the firmware (download mode needed)

### ISSUE THREAD

**Issue by igor1019** [h-RAT/EvilCrowRF_Custom_Firmware_CC1101_FlipperZero#11]
How can I put my evil crow rf v2 in download mode to flash firmware?
I have been receiving this error below in ESPHome-flasher when installing the firmware:

Using 'COM10' as serial port.
Connecting......................................
Unexpected error: ESP is not in flash boot mode. If your board has a flashing pin, try again while keeping it pressed.

Thank you so much!

**Comment by h-RAT** [comment]
> How can I put my evil crow rf v2 in download mode to flash firmware? I have been receiving this error below in ESPHome-flasher when installing the firmware:
> 
> Using 'COM10' as serial port. Connecting...................................... Unexpected error: ESP is not in flash boot mode. If your board has a flashing pin, try again while keeping it pressed.
> 
> Thank you so much!

Hi, your board should go into download mode automatically but on some OS this does not work.

So here is how I do it:

When you click "Upload", you should see something like this:

  Connecting......._____........._____.........

You must press the "Reset" button on your card just before the first "_" character appears.

If you fail on the first attempt it doesn't matter, you can try 4 or 5 times before the upload is canceled and you get an error message.

If you don't see any "_" characters, like in your example, you should see a change in speed when writing the "." characters, it's hard to explain but that's when you should press the “Reset” button

-------------------

You can also try to reset your card with this command:

"esptool --chip esp32 erase_flash"

And then your card will automatically go into download mode during your next upload.

-------------------

Or you can also try using Linux or a virtual machine to upload your sketch.
