### ISSUE TITLE
Error acess page 192.168.4.1

### ISSUE THREAD

**Issue by ronaldosegundojr** [h-RAT/EvilCrowRF_Custom_Firmware_CC1101_FlipperZero#13]
Hello, how are you?
I recently acquired 2 Evil Crow for testing
Both came with another, older firmware, I accessed the firmware of both and updated via the web at 192.168.4.1/update

However, after the update, only one of the Evil Crows worked correctly with the new firmware.

The other evil crow changed the name of the wifi network to ECRF but when accessing 192.168.4.1, it does not load the configured home page.
However, if I type 192.168.4.1/update the update page loads.

I've tested other SD cards, I've tested it on several computers, I've reinstalled the old firmware, the new firmware too and still have the same problem, do you know how to help me?

thanks!

**Comment by h-RAT** [comment]
Hi, sorry I'm not responsible for the devices, I'm just the author of the firmware.

Maybe your devices are clones?

You can join the EvilCrowRF discord communities if you want to ask questions.

Discord Group: https://discord.gg/Rb2j3jA5Ym
