### ISSUE TITLE
Can't scan

### ISSUE THREAD

**Issue by hhhomega** [h-RAT/EvilCrowRF_Custom_Firmware_CC1101_FlipperZero#14]
Can't scan.
The rest is fine

**Comment by h-RAT** [comment]
Hi, please, thanks.

Please write sentences and explain your problem to try to resolve it.

You can also chat on discord.

Discord Group: https://discord.gg/Rb2j3jA5Ym

**Comment by hhhomega** [comment]
Hi!,
the problem was in rssi -50.
solved rssi -60...-70 for 433.92 mhz, but for 315.00mhz i have allways problem.
I think is bad chose bandwidth,datarate. i will continue testing.
For ASK/OOK deviation doesn't matter . Am i rigth?
thx

**Comment by h-RAT** [comment]
The scanner uses predefined settings, you cannot adjust anything except the RSSI. 

I will look and fix the issue for the next update. 

Thanks for your feedback
