### ISSUE TITLE
Battery Compatibility Issue with this Firmware Compared to Original EvilCrowRF-V2 Firmware

### ISSUE THREAD

**Issue by marceloapd** [h-RAT/EvilCrowRF_Custom_Firmware_CC1101_FlipperZero#17]
I hope this message finds you well. I'm writing to highlight a significant issue with the custom firmware compared to the original EvilCrowRF-V2 firmware.

Issue Description:
After installing this custom firmware, I've encountered problems with battery compatibility and power management. Unlike with the original firmware, the device struggles to maintain power and behaves unpredictably with the same battery setup that functions flawlessly on the original firmware.

Reference to Original Firmware:
The original firmware, developed by Joel Serna and outlined in the [EvilCrowRF-V2 GitHub repository](https://github.com/joelsernamoreno/EvilCrowRF-V2), effectively manages power, as seen in its "Power Management" section. This discrepancy is concerning as it impacts the device's reliability and efficiency.

Thank you for considering my feedback. I am keen to see improvements that align the custom firmware's battery management with the original's capabilities and continue my support for the EvilCrowRF project.

Best regards,

Marceloapd

**Comment by h-RAT** [comment]
Hi, yes actually, no battery management is integrated into this firmware.

I would consider adding it in the next version.

Thanks for your feedback

**Comment by lukeswitz** [comment]
Hi @h-RAT,

I appreciate the work you've done on this project, but I wanted to bring up a critical concern—power management. I understand this isn't an open-source project, though it's unclear why you chose GitHub unless it was primarily for promotion. I respect your stance on monetizing your work, and perhaps Patreon for paid releases could be a viable option for you.

That said, until such a solution is in place, I'd strongly suggest making the code open for review and collaboration. As it stands, flashing firmware I can’t review, especially when the developer isn’t open to collaboration, raises concerns. This is not a critique of your effort—quite the opposite. There’s a group of us who could contribute to improving the code, fixing bugs, and adding necessary features, such as proper power management.

Using Ghidra, I’ve reversed most of the code to work around these issues, but this is a temporary fix. Without proper power management, there’s a risk of hardware damage, and it's crucial to address this before any incidents occur. If nothing else, a clear disclaimer about this risk would be appreciated.

Please don’t take this the wrong way—your work is impressive, and everyone here acknowledges that. We just want to collaborate and help improve what you’ve built. After all, the goal of this community is to share and build upon cool projects, not to lock them away as proprietary.

Take care, and I hope you’ll consider either adding these features or opening the source to allow broader input before any major issues arise.

Best regards
