### ISSUE TITLE
rollback/rolljam capture not working

### ISSUE THREAD

**Issue by slikkmulah** [h-RAT/EvilCrowRF_Custom_Firmware_CC1101_FlipperZero#6]
just updated to the beta that was just released. It seems that when trying to perform a rollback or rolljam attack that the transmission being received is not being captured correctly. To be more specific it is showing that the signal has been captured but the area that usually shows the binary is blank and when i click on replay I get an error saying that the transmission was not saved... Anyone else having this issue?

Thanks.

**Comment by h-RAT** [comment]
Your problem is solved?

Otherwise if it can help other people:

Clear your cache and use a private browser to prevent any issues.

Otherwise the only reason you receive a null result is that you only receive noise (probably from the jammer), move the jammer away, or reduce the power.

**Comment by slikkmulah** [comment]
> Your problem is solved?
> 
> 
> 
> Otherwise if it can help other people:
> 
> 
> 
> Clear your cache and use a private browser to prevent any issues.
> 
> 
> 
> Otherwise the only reason you receive a null result is that you only receive noise (probably from the jammer), move the jammer away, or reduce the power.





I have 2 devices and I realized that the one that was having the problem was the one I plugged a lipo battery into. I didnt check the polarity first and immediately pulled the connector after realizing my mistake.

I thought the device hadn't suffered any damage but I guess I was wrong because now it is suffering with errors :/

(Guys if you get a battery. Always, always check polarity before connecting!)

**Comment by xzibit1** [comment]
Will do...sell me ,complete funktional rollyam
.cann you do that?????jam and 2 signals record sistem???
THANK,s

pet, 4. kol 2023. 03:19 slikkmulah ***@***.***> je napisao:
